// Objective-C API for talking to github.com/liujianping/golib Go package.
//   gobind -lang=objc github.com/liujianping/golib
//
// File is generated by gobind. Do not edit.

#ifndef __Golib_H__
#define __Golib_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT NSString* _Nonnull GolibDirectory(NSString* _Nullable path, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT NSString* _Nonnull GolibGreetings(NSString* _Nullable name);

FOUNDATION_EXPORT BOOL GolibNumberError(long num, long* _Nullable ret0_, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL GolibSqliteCrud(NSString* _Nullable dir, NSError* _Nullable* _Nullable error);

FOUNDATION_EXPORT BOOL GolibWalkDirectory(NSString* _Nullable path, NSError* _Nullable* _Nullable error);

#endif
