
// Objective-C API for talking to the following Go packages
//
//	github.com/liujianping/golib
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Golib_FRAMEWORK_H__
#define __Golib_FRAMEWORK_H__

#include "Golib.objc.h"
#include "Universe.objc.h"

#endif
